disabled_rules:
  - identifier_name
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - nesting

  # 향후 제거
  - type_body_length
  - function_body_length
  - force_cast
  - file_length
  - line_length
