name: Build and Test TrainTrain App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  XCODE_VERSION: 14.2
  WORKSPACE: "TrainTrain.xcworkspace"
  SCHEME: "TrainTrain"
  DESTINATION: "platform=iOS Simulator,name=iPhone 14 Pro"
  CLONED_PACKAGES_DIRECTORY: "ClonedPackages"

jobs:
  build:
    name: Build and Test default scheme
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Build Environment
        run: |
          if ! which xcbeautify > /dev/null 2>$1; then
            brew install xcbeautify;
          fi

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Cache cloned packages directory
        id: cache-cloned-packages
        uses: actions/cache@v3
        with:
          path: "TrainTrain/${{ env.CLONED_PACKAGES_DIRECTORY }}"
          key: ${{ runner.os }}-cloned-packages-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-cloned-packages-

      - name: Build workspace with cloned packages directory
        run: |
          cd TrainTrain
          set -o pipefail && xcodebuild clean build-for-testing -workspace "${{ env.WORKSPACE }}" -scheme "${{ env.SCHEME }}" -destination "${{ env.DESTINATION }}" -clonedSourcePackagesDirPath "${{ env.CLONED_PACKAGES_DIRECTORY }}" | xcbeautify

      - name: Save cache
        if: success()
        uses: actions/cache@v3
        with:
          path: "TrainTrain/${{ env.CLONED_PACKAGES_DIRECTORY }}"
          key: ${{ runner.os }}-cloned-packages-${{ hashFiles('**/Packages.resolved') }}

      - name: Test with cloned packages directory
        run: |
          cd TrainTrain
          set -o pipefail && xcodebuild test-without-building -workspace "${{ env.WORKSPACE }}" -scheme "${{ env.SCHEME }}" -destination "${{ env.DESTINATION }}" -disableAutomaticPackageResolution -clonedSourcePackagesDirPath "${{ env.CLONED_PACKAGES_DIRECTORY }}" | xcbeautify
